name: Core Binary Build
on:
  push:
    branches: [ nodejs-release, main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Cache Node packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
        path: |
          ./node_modules
    - name: Setup dependencies
      run: npm install
    - name: Build the packages
      run: ./pkg-build.sh
    - name: Archive binary files
      uses: actions/upload-artifact@v2
      with:
        name: binary-files
        path: |
          bin/*
